dist: bionic
language: python
cache: pip
matrix:
  fast_finish: true
  include:
    - python: 3.8
      env: TOXENV=py38-dj22-postgresql
      addons:
        postgresql: "9.5"

    - python: 3.8
      env: TOXENV=py38-dj30-postgresql
      addons:
        postgresql: "9.5"

    - python: 3.8
      env: TOXENV=py38-dj31-postgresql DJANGO_SELENIUM_TESTS=True
      before_install:
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
        - mkdir geckodriver && tar zxvf geckodriver-v0.27.0-linux64.tar.gz -C geckodriver
        - export PATH=$PATH:$PWD/geckodriver
      addons:
        firefox: latest
        postgresql: "9.5"
    - python: 3.8
      env: TOXENV=py38-dj22-mariadb
      addons:
        mariadb: "10.3"
      script:
        # working around https://travis-ci.community/t/mariadb-build-error-with-xenial/3160
        - mysql -u root -e "DROP USER IF EXISTS 'travis'@'%';"
        - mysql -u root -e "CREATE USER 'travis'@'%';"
        - mysql -u root -e "CREATE DATABASE debug_toolbar;"
        - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'%';";
        - tox -v
    - python: 3.8
      env: TOXENV=py38-dj30-mariadb
      addons:
        mariadb: "10.3"
      script:
        # working around https://travis-ci.community/t/mariadb-build-error-with-xenial/3160
        - mysql -u root -e "DROP USER IF EXISTS 'travis'@'%';"
        - mysql -u root -e "CREATE USER 'travis'@'%';"
        - mysql -u root -e "CREATE DATABASE debug_toolbar;"
        - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'%';";
        - tox -v
    - python: 3.8
      env: TOXENV=py38-dj31-mariadb
      addons:
        mariadb: "10.3"
      script:
        # working around https://travis-ci.community/t/mariadb-build-error-with-xenial/3160
        - mysql -u root -e "DROP USER IF EXISTS 'travis'@'%';"
        - mysql -u root -e "CREATE USER 'travis'@'%';"
        - mysql -u root -e "CREATE DATABASE debug_toolbar;"
        - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'%';";
        - tox -v
  allow_failures:
    - env: TOXENV=py36-djmaster-sqlite
    - env: TOXENV=py37-djmaster-sqlite
    - env: TOXENV=py38-djmaster-sqlite
    - env: TOXENV=py38-djmaster-postgresql
    - env: TOXENV=py38-djmaster-mariadb

install:
  - pip install tox codecov
script:
  - tox -v
after_success:
  - codecov
